DROP TABLE IF EXISTS PORTFOLIOS;

CREATE TABLE PORTFOLIOS (
	ID INT NOT NULL AUTO_INCREMENT,
	ACCOUNT_TYPE VARCHAR(10),
	ACCOUNT_TYPE_OTHER_DESCRIPTION VARCHAR(255),
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS HOLDINGS; 

CREATE TABLE PUBLIC.HOLDINGS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	PORTFOLIO_ID INTEGER NOT NULL,
	SYMBOL VARCHAR(7) NOT NULL,
	EXCHANGE VARCHAR(15) NOT NULL,
	NUMBER_OF_SHARES INTEGER,
	BOOK_VALUE DOUBLE,
	DIVIDEND_YIELD DOUBLE,
	DIVIDEND_PER_SHARE DOUBLE,
	SHARE_CURRENT_VALUE DOUBLE,
	SHARE_MAX_VALUE DOUBLE,
	CONSTRAINT HOLDINGS_PK PRIMARY KEY (ID)
);
